version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: wura_postgres
    restart: always
    environment:
      POSTGRES_USER: wura_admin
      POSTGRES_PASSWORD: wura_password_local
      POSTGRES_DB: wura_db
    ports:
      - "5432:5432"
    volumes:
      - wura_pgdata:/var/lib/postgresql/data

volumes:
  wura_pgdata:
